// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userUnregister.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnRegisterRequest struct {
	MobileNum            string   `protobuf:"bytes,1,opt,name=mobileNum,proto3" json:"mobileNum,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterRequest) Reset()         { *m = UnRegisterRequest{} }
func (m *UnRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnRegisterRequest) ProtoMessage()    {}
func (*UnRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd7ca994e8fcc2f, []int{0}
}

func (m *UnRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterRequest.Unmarshal(m, b)
}
func (m *UnRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UnRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterRequest.Merge(m, src)
}
func (m *UnRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnRegisterRequest.Size(m)
}
func (m *UnRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterRequest proto.InternalMessageInfo

func (m *UnRegisterRequest) GetMobileNum() string {
	if m != nil {
		return m.MobileNum
	}
	return ""
}

func (m *UnRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnRegisterResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterResponse) Reset()         { *m = UnRegisterResponse{} }
func (m *UnRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UnRegisterResponse) ProtoMessage()    {}
func (*UnRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd7ca994e8fcc2f, []int{1}
}

func (m *UnRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterResponse.Unmarshal(m, b)
}
func (m *UnRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UnRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterResponse.Merge(m, src)
}
func (m *UnRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UnRegisterResponse.Size(m)
}
func (m *UnRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterResponse proto.InternalMessageInfo

func (m *UnRegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UnRegisterRequest)(nil), "go.micro.api.unregister.UnRegisterRequest")
	proto.RegisterType((*UnRegisterResponse)(nil), "go.micro.api.unregister.UnRegisterResponse")
}

func init() { proto.RegisterFile("userUnregister.proto", fileDescriptor_0cd7ca994e8fcc2f) }

var fileDescriptor_0cd7ca994e8fcc2f = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x2d, 0x4e, 0x2d,
	0x0a, 0xcd, 0x2b, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0x4f, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b,
	0x85, 0x4b, 0x2b, 0xb9, 0x72, 0x09, 0x86, 0xe6, 0x05, 0x41, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0xb9, 0xf9, 0x49, 0x99, 0x39, 0xa9, 0x7e, 0xa5, 0xb9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x26, 0xb0, 0x04, 0x98, 0xad, 0xa4, 0xc6, 0x25, 0x84, 0x6c, 0x4c, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0xd4, 0x04, 0x10, 0xd3, 0xa8, 0x92, 0x8b,
	0x0b, 0xa1, 0x4e, 0x28, 0x9b, 0x8b, 0x0f, 0xc1, 0x0b, 0x2d, 0x4e, 0x2d, 0x12, 0xd2, 0xd2, 0xc3,
	0xe1, 0x50, 0x3d, 0x0c, 0x57, 0x4a, 0x69, 0x13, 0xa5, 0x16, 0xe2, 0x14, 0x25, 0x86, 0x24, 0x36,
	0x70, 0x48, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0xc1, 0xdc, 0x32, 0x21, 0x01, 0x00,
	0x00,
}
