// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userRegister.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	MobileNum            string   `protobuf:"bytes,1,opt,name=mobileNum,proto3" json:"mobileNum,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd0216664a6472cd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobileNum() string {
	if m != nil {
		return m.MobileNum
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd0216664a6472cd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UnRegRequest struct {
	MobileNum            string   `protobuf:"bytes,1,opt,name=mobileNum,proto3" json:"mobileNum,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegRequest) Reset()         { *m = UnRegRequest{} }
func (m *UnRegRequest) String() string { return proto.CompactTextString(m) }
func (*UnRegRequest) ProtoMessage()    {}
func (*UnRegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd0216664a6472cd, []int{2}
}

func (m *UnRegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegRequest.Unmarshal(m, b)
}
func (m *UnRegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegRequest.Marshal(b, m, deterministic)
}
func (m *UnRegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegRequest.Merge(m, src)
}
func (m *UnRegRequest) XXX_Size() int {
	return xxx_messageInfo_UnRegRequest.Size(m)
}
func (m *UnRegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegRequest proto.InternalMessageInfo

func (m *UnRegRequest) GetMobileNum() string {
	if m != nil {
		return m.MobileNum
	}
	return ""
}

func (m *UnRegRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnRegRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UnRegResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegResponse) Reset()         { *m = UnRegResponse{} }
func (m *UnRegResponse) String() string { return proto.CompactTextString(m) }
func (*UnRegResponse) ProtoMessage()    {}
func (*UnRegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd0216664a6472cd, []int{3}
}

func (m *UnRegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegResponse.Unmarshal(m, b)
}
func (m *UnRegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegResponse.Marshal(b, m, deterministic)
}
func (m *UnRegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegResponse.Merge(m, src)
}
func (m *UnRegResponse) XXX_Size() int {
	return xxx_messageInfo_UnRegResponse.Size(m)
}
func (m *UnRegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegResponse proto.InternalMessageInfo

func (m *UnRegResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.api.register.Request")
	proto.RegisterType((*Response)(nil), "go.micro.api.register.Response")
	proto.RegisterType((*UnRegRequest)(nil), "go.micro.api.register.UnRegRequest")
	proto.RegisterType((*UnRegResponse)(nil), "go.micro.api.register.UnRegResponse")
}

func init() { proto.RegisterFile("userRegister.proto", fileDescriptor_dd0216664a6472cd) }

var fileDescriptor_dd0216664a6472cd = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0x0a, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x4d, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x82, 0x4a,
	0x2a, 0x85, 0x73, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0xe6,
	0xe6, 0x27, 0x65, 0xe6, 0xa4, 0xfa, 0x95, 0xe6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21,
	0x04, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x12, 0x60, 0xb6, 0x90,
	0x14, 0x17, 0x47, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x33, 0x58, 0x1c, 0xce,
	0x57, 0x92, 0xe1, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe0, 0x62,
	0xce, 0x2d, 0x4e, 0x87, 0x9a, 0x09, 0x62, 0x2a, 0xc5, 0x70, 0xf1, 0x84, 0xe6, 0x05, 0xa5, 0xa6,
	0xd3, 0xc6, 0x6e, 0x45, 0x2e, 0x5e, 0xa8, 0xe9, 0xb8, 0x1c, 0x60, 0xb4, 0x87, 0x11, 0xe4, 0x3e,
	0x48, 0x20, 0x08, 0x05, 0x72, 0xf1, 0xc0, 0xd8, 0xa1, 0xc5, 0xa9, 0x45, 0x42, 0x72, 0x7a, 0x58,
	0x03, 0x4b, 0x0f, 0xea, 0x5a, 0x29, 0x79, 0x9c, 0xf2, 0x10, 0xfb, 0x94, 0x18, 0x84, 0x62, 0xb9,
	0xf8, 0xc0, 0x4e, 0x40, 0x18, 0xaa, 0x8c, 0x43, 0x13, 0x72, 0x38, 0x48, 0xa9, 0xe0, 0x57, 0x04,
	0x33, 0x3e, 0x89, 0x0d, 0x1c, 0xa9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x3f, 0x06,
	0xae, 0xea, 0x01, 0x00, 0x00,
}
