// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userUnregister.proto

package go_micro_api_unregister

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	MobileNum            string   `protobuf:"bytes,1,opt,name=mobileNum,proto3" json:"mobileNum,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd7ca994e8fcc2f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobileNum() string {
	if m != nil {
		return m.MobileNum
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd7ca994e8fcc2f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.api.unregister.Request")
	proto.RegisterType((*Response)(nil), "go.micro.api.unregister.Response")
}

func init() { proto.RegisterFile("userUnregister.proto", fileDescriptor_0cd7ca994e8fcc2f) }

var fileDescriptor_0cd7ca994e8fcc2f = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x31, 0x0b, 0xc2, 0x40,
	0x0c, 0x85, 0xad, 0x8a, 0xda, 0x0c, 0x22, 0x41, 0xb0, 0x48, 0x87, 0xda, 0xc9, 0xe9, 0x06, 0x1d,
	0xfd, 0x0f, 0x0e, 0x07, 0xc5, 0xb9, 0x95, 0x50, 0x0e, 0xbc, 0xbb, 0x9a, 0xf4, 0xfe, 0xbf, 0x58,
	0x0f, 0x3b, 0xe9, 0xf6, 0x92, 0x97, 0xf0, 0xbe, 0x07, 0xdb, 0x20, 0xc4, 0x95, 0x63, 0x6a, 0x8d,
	0xf4, 0xc4, 0xaa, 0x63, 0xdf, 0x7b, 0xdc, 0xb5, 0x5e, 0x59, 0x73, 0x67, 0xaf, 0xea, 0xce, 0xa8,
	0xf0, 0xb5, 0xcb, 0x0b, 0x2c, 0x35, 0x3d, 0x03, 0x49, 0x8f, 0x39, 0xa4, 0xd6, 0x37, 0xe6, 0x41,
	0xd7, 0x60, 0xb3, 0xa4, 0x48, 0x8e, 0xa9, 0x1e, 0x17, 0x88, 0x30, 0x77, 0xb5, 0xa5, 0x6c, 0x3a,
	0x18, 0x83, 0x2e, 0x73, 0x58, 0x69, 0x92, 0xce, 0x3b, 0x21, 0xdc, 0xc0, 0xcc, 0x4a, 0x1b, 0xff,
	0xde, 0xf2, 0x44, 0x00, 0x95, 0xd3, 0x31, 0x08, 0x6f, 0xb0, 0x1e, 0xa7, 0x4a, 0x88, 0xb1, 0x50,
	0x3f, 0xa0, 0x54, 0x24, 0xda, 0x1f, 0xfe, 0x5c, 0x7c, 0x62, 0xcb, 0x49, 0xb3, 0x18, 0x1a, 0x9e,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x29, 0x6f, 0x6a, 0xf9, 0x00, 0x00, 0x00,
}
