// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userUnregister.proto

package go_micro_api_unregister

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UnRegister service

type UnRegisterService interface {
	UnRegisterUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type unRegisterService struct {
	c    client.Client
	name string
}

func NewUnRegisterService(name string, c client.Client) UnRegisterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.unregister"
	}
	return &unRegisterService{
		c:    c,
		name: name,
	}
}

func (c *unRegisterService) UnRegisterUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UnRegister.UnRegisterUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UnRegister service

type UnRegisterHandler interface {
	UnRegisterUser(context.Context, *Request, *Response) error
}

func RegisterUnRegisterHandler(s server.Server, hdlr UnRegisterHandler, opts ...server.HandlerOption) error {
	type unRegister interface {
		UnRegisterUser(ctx context.Context, in *Request, out *Response) error
	}
	type UnRegister struct {
		unRegister
	}
	h := &unRegisterHandler{hdlr}
	return s.Handle(s.NewHandler(&UnRegister{h}, opts...))
}

type unRegisterHandler struct {
	UnRegisterHandler
}

func (h *unRegisterHandler) UnRegisterUser(ctx context.Context, in *Request, out *Response) error {
	return h.UnRegisterHandler.UnRegisterUser(ctx, in, out)
}
